### ISSUE TITLE
Battery wird immer mit 0% angezeigt

### ISSUE THREAD

**Issue by zionusxx** [unl0ck/homeassistant-addon-viessmann-gridbox#16]
![Sensoren](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/163358777/c4850fdf-997c-43a4-998f-e11f2212959f)

**Comment by zionusxx** [comment]
Wo sind denn die Logdateien des Addons zu finden, außer im Reiter Protokoll?

**Comment by unl0ck** [comment]
bitte mit 1.1.3 testen

**Comment by zionusxx** [comment]
Battery:
power sollte ggf ein eigener Sensor mit Einheit Watt sein! Dieser zeigt an wieviel Watt momentan in bzw. aus  der Batterie geladen wird.

**Comment by zionusxx** [comment]
batterie_power_sensor_info = SensorInfo(name="BatteriePower", device_class="power", unique_id="gridbox_battery_power", device=device_info, unit_of_measurement="W")
    battery_power_settings = Settings(mqtt=mqtt_settings, entity= batterie_power_sensor_info)

**Comment by zionusxx** [comment]
Momentan wird der Wert, der eigentlich in Watt angezeigt werden soll als Prozent mit Faktor 10 angezeigt .

![IMG_3138](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/163358777/f8e9755a-c2c0-49da-ba3b-c0d1bf22c399)
![IMG_3137](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/163358777/9b877c5e-cac6-4fc8-8510-d40531cb13c9)

**Comment by zionusxx** [comment]
Bei dem ursprünglichen Sensor mal das Prozent als Einheit weglassen:

battery_sensor_info = SensorInfo(name="Battery", device_class="battery", unique_id="gridbox_battery", device=device_info, unit_of_measurement="")
    battery_settings = Settings(mqtt=mqtt_settings, entity=battery_sensor_info)


battery_sensor.set_state(measurement["stateOfCharge"])
battery_power_sensor.set_state(measurement["power"])

**Comment by unl0ck** [comment]
ja das problem ist hier ich muss mich auf test daten verlassen, deine bilder hatten 2 verschiedene stände gezeigt, in dem andren issue, 
ich konnte das dann nicht mappen oder erkennen, was was ist.
wäre gut wenn du mir ein screenshot der daten schicken könnten sowie hier 
![image](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/25794700/2434e3b1-e7fa-4f9b-8b57-1140b4ae6d31)

**Comment by unl0ck** [comment]
So hab mir nochmal nach der Doku gesucht mit 1.2.0 sollte die 0% weg sein problem war ein casting problem, bitte einmal abtesten.
aber wenn du mir dennoch so einen Ausdruck schicken könntest, dann könnte ich zukünftig unit tests dagegen schreiben, 
bitte code als code teilen erhöht die Lesbarkeit.

**Comment by unl0ck** [comment]
@zionusxx  bitte einmal bescheid geben ob nun keine 0% mehr da sind.

**Comment by zionusxx** [comment]
Die Sensoren  Gridbox Sum Capacity, Sum Lebel, Sum Power 
sind genau das, was ich gebraucht habe.
Vielen dank!

**Comment by unl0ck** [comment]
kannst du mir bitte ein screenshot schicken?

**Comment by zionusxx** [comment]
![IMG_3143](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/163358777/686f2ddc-1476-4526-92c5-53b5041e1e8d)
![IMG_3142](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/163358777/a1c22927-285c-451d-8f55-ccd67010fc40)

Die Sensoren Gridbox Sum Capacity, Sum Lebel, Sum Power
sind genau das, was ich gebraucht habe.

Es wir wird bei mir zwar immer noch Battery mit dem falschen Prozentwert angezeigt. Das kann aber auch noch eine Altlast aus dem „cache“ sein.

Vielen dank! Das hat mir sehr weitergeholfen.
