### ISSUE TITLE
Bitte weitere Sensoren bereitstellen

### ISSUE THREAD

**Issue by zionusxx** [unl0ck/homeassistant-addon-viessmann-gridbox#17]
Bitte (auf vielfachen Wunsch) folgende Werte aus den Live-Daten als Sensoren bereitstellen:

"batteries":[
      { "power": 500,
         "stateOfCharge":0
      }
   ],
   "battery":{
      "power": 500,
      "stateOfCharge":0

"consumption":814,
"directConsumption":124,
"directConsumptionHeatPump":124,
"directConsumptionHousehold":0,

Danke und viele Grüße

**Comment by zionusxx** [comment]
![11,8 kWp](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/163358777/e1383449-b182-4840-8a31-5714e6be8e74)

Das wären dann alle relevanten Live-Daten. 
Man benötigt diese übrigens auch zwingend für evcc.

**Comment by unl0ck** [comment]
bitte mit 1.1.3 prüfen

**Comment by zionusxx** [comment]
Bitte auch noch den Sensor / die Sensoren integrieren:

consumption":814,
"directConsumption":124,
"directConsumptionHeatPump":124,
"directConsumptionHousehold":0,

**Comment by zionusxx** [comment]
consumption_sensor_info = SensorInfo(name="Consumption", device_class="power", unique_id="gridbox_consumption", device=device_info, unit_of_measurement="W")
    consumption_settings = Settings(mqtt=mqtt_settings, entity= consumption_sensor_info)

direct_consumption_sensor_info = SensorInfo(name="DirectConsumption", device_class="power", unique_id="gridbox_direct_consumption", device=device_info, unit_of_measurement="W")
    direct_consumption_settings = Settings(mqtt=mqtt_settings, entity= direct_consumption_sensor_info)

Usw. Für alle Consumption Werte

**Comment by zionusxx** [comment]
consumption_sensor.set_state(measurement["consumption"])

direct_consumption_sensor.set_state(measurement["directConsumption"])

usw.

**Comment by unl0ck** [comment]
ich hätte gern einen Plausiblen Namen für die Sensoren. 
kann die auch einfach so mappen, ist halt wenig aussagekräftig

**Comment by zionusxx** [comment]
consumption: Ist vermutlich die Summe aller Verbraucher

directConsumptionHeatPump:  Ist nur der Verbrauch der Wärmepumpe 

directConsumptionHousehold:  Ist der restliche Haus-Verbrauch

directConsumption weiß nicht genau was dieser Wert bedeutet, ist mir nicht ganz klar. Ich würde es trotzdem mal zusätzlich als Sensor liefern.

Für die Namen kannst Du gerne was aussagekräftiges auswählen.

**Comment by zionusxx** [comment]
Mein Vorschlag für die Namen wären:

„Consumption total“ für consumption
„Consumption direct“ für directConsumption
„Consumption Heat Pump“ für directConsumptionHeatPump
„Consumption Household“ für  directConsumptionHousehold

**Comment by zionusxx** [comment]
@unl0ck : Was hältst Du denn von den Vorschlägen?
Vielleicht reicht es auch erst einmal zwei Sensoren zu implementieren : "Consumption Heat Pump" und „Consumption Household“.

Die Implemtierung wäre doch sinnvoll, um zwischen den verschiedenen Verbrauchern im Haus unterscheiden zu können.
Wieviel Watt verbraucht gerade die Wärmepumpe (Consumption Heat Pump) im Vergleich zum restlichen Verbrauch. usw.

**Comment by unl0ck** [comment]
@zionusxx  sorry grad viel um die ohren aber die 2 hab ich jetzt mal eingebaut, wollte eigentlich noch bissle umbauen, hab da in dem Addon auch bissle murks gemacht was die überwachung angeht, komm nur leider grad ned zu.

**Comment by zionusxx** [comment]
@unl0ck Danke für die Umsetzung.
Leider werden momentan die Werte der Sensoren nicht mehr aktualisiert.
Ob das nur an diesem Fehler liegt, kann ich nicht beurteilen:

/run.sh: line 11: MqttPort: unbound variable

Ich hab zumindest mal einen Issue dafür angelegt.

**Comment by unl0ck** [comment]
Ah ja ich schau mir das an Mist okay mit freundlichen GrüßenSimon HelmingOn 17. Apr 2024, at 18:35, zionusxx ***@***.***> wrote:﻿
@unl0ck Danke für die Umsetzung.
Leider werden momentan die Werte der Sensoren nicht mehr aktualisiert.
Ob das nur an diesem Fehler liegt, kann ich nicht beurteilen:
/run.sh: line 11: MqttPort: unbound variable
Ich hab zumindest mal einen Issue dafür angelegt.

**Comment by unl0ck** [comment]
ja fehler liegt vermutlich daran

**Comment by zionusxx** [comment]
@unl0ck : Mittlerweile konnte ich die Version 1.4.5 testen. Der Bug ist behoben und das Addon funktioniert wieder. Vielen Dank.

Die neuen Sensoren. DirectConsumption Heat Pump" und „DirectConsumption Household“ sind nun auch verfügbar. 
Allerdings hatte ich mich leider bezüglich des Inhalts geirrt. „Direct“ bedeutet wohl hier, nur was an erzeugtem Strom direkt für Wärmepumpe bzw. Haushalt verbraucht wird.

Wäre es denn ein großer Aufwand auch noch folgende Sensoren zu integrieren:

totalConsumption
consumption 

Die Werte ohne „Direct“ sind nämlich der Verbrauch des Haushalts unabhängig von der PV Produktion.

Sorry das ich’s jetzt erst richtig verstanden habe, wo ich die Werte in Aktion sehen kann.

**Comment by msommerx** [comment]
@zionusxx wo verwendest du die Sensoren? Im Energy Dashboard?
Laut HA Doku müssten die Sensoren mit der device_class energy versehen sein. 
[https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities](url)
@unl0ck Ich bin erst seit kurzem auf HA unterwegs. Gibt es einen speziellen Grund, dass sie als power und nicht energy definiert sind?

**Comment by unl0ck** [comment]
@msommerx  alle Wh sind Energy und W sind Power
![image](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/25794700/522b6c66-e4eb-42a2-bbb3-7c6489798b18)
![image](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/25794700/28937429-c436-490f-b765-74b6ecf6ed3e)
einen fehler hatte ich gefunden werd das hochladen

**Comment by unl0ck** [comment]
@zionusxx brauchst du noch welche ? würde sonst das ticket erst einmal schließen

**Comment by zionusxx** [comment]
Wäre es denn ein großer Aufwand auch noch folgende Sensoren zu integrieren:

totalConsumption
consumption

**Comment by zionusxx** [comment]
> @zionusxx brauchst du noch welche ? würde sonst das ticket erst einmal schließen

Wäre es denn ein großer Aufwand auch noch folgende Sensoren zu integrieren?

totalConsumption
consumption

**Comment by zionusxx** [comment]
> @zionusxx wo verwendest du die Sensoren? Im Energy Dashboard?
> Laut HA Doku müssten die Sensoren mit der device_class energy versehen sein.
> [https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities](url)

@msommerx : Ich nutze die Sensoren um die Werte aus der Live View Webseite der Gridbox in anderen Systemen wie z.B Homeassistant, Openhab und evcc via mqtt nutzen zu können.
Für das Energy Dashboard in Homeassistant habe ich Helfer Entitäten mit Riemann Summenintegralsensoren erstellt, um die Werte von W in Wh umzurechnen.

**Comment by zionusxx** [comment]
> > @zionusxx brauchst du noch welche ? würde sonst das ticket erst einmal schließen
> 
> Wäre es denn ein großer Aufwand auch noch folgende Sensoren zu integrieren?
> 
> totalConsumption consumption

totalConsumption
consumption

Die Sensoren sind jetzt verfügbar, Vielen Dank.
Ticket kann geschlossen werden.
