### ISSUE TITLE
Batterieladestand wird mit dem Wert der (Ent-)Ladeleistung angegeben

### ISSUE THREAD

**Issue by FRMB6** [unl0ck/homeassistant-addon-viessmann-gridbox#18]
![image](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/163857685/61490b18-0b6c-4871-9465-ebbb11913ece)

Batterieladezustand schwankt zwicshen -400% und +400%, scheint also der Wert der (Ent-)ladeleistung zu sein.

Die Ladeleistung darf aber gerne als Extra Wert mit ausgegeben werden!

**Comment by unl0ck** [comment]
@FRMB6  danke dir, mittagspause kurz bissle rum gefummelt, ohne IDE mit 1.3.0 solltest nun was sehen.
da der andrang scheinbar größer ist, werd ich mal schauen das ich das ganze ein wenig schöner schreibe den code, nicht mehr quick and dirty ebenso mit der watchdog, hab bei mir festgestellt, manchmal erhängt sich das addon.

**Comment by unl0ck** [comment]
@FRMB6 bitte mal 1.3.0 testen und bescheid geben

**Comment by unl0ck** [comment]
musst nicht manuell
wird automatisch dir angezeigt
