### ISSUE TITLE
run.sh: line 11: MqttPort: unbound variable

### ISSUE THREAD

**Issue by zionusxx** [unl0ck/homeassistant-addon-viessmann-gridbox#19]
Hallo @unl0ck im Logfile gibt es nun folgenden Fehler:
 /run.sh: line 11: MqttPort: unbound variable

Lösung:

export FiatChamp_MqttPort=$(bashio::config 'OverrideMqttPort')

muss vermutlich so heißen:

export MqttPort=$(bashio::config 'OverrideMqttPort')

**Comment by unl0ck** [comment]
ja ich muss mir mal was überlegen, dass ich das im Vorfeld testen kann, wie ich das umsetzen kann. sorry dafür, hoffe ich. hab das problem gleich behoben

**Comment by unl0ck** [comment]
fixed in 1.4.5

**Comment by zionusxx** [comment]
@unl0ck Danke fürs Fixen. Noch wird aber das Update auf die Version 1.4.5 in Home Assistant nicht angeboten.

**Comment by unl0ck** [comment]
@zionusxx  nein sollte schon da sein ich hab es schon erhalten,

**Comment by unl0ck** [comment]
@zionusxx update erhalten?
