### ISSUE TITLE
Verbindung zur Gridbox Cloud wird unregelmäßig getrennt

### ISSUE THREAD

**Issue by zionusxx** [unl0ck/homeassistant-addon-viessmann-gridbox#21]
Hallo @unl0ck,
die Verbindung zur Gridbox Cloud wird unregelmäßig getrennt.
Das Problem ist Dir ja schon bekannt, trotzdem habe ich mal einen Issue dazu aufgemacht.

Denn mittlerweile habe ich auch einen Workaround gefunden, um das Addon neu zu starten, falls die Session zur Gridbox Cloud wieder getrennt wurde. Der Workaround kann benutzt werden, bis das Problem gefixt wurde bzw. Watchdog funktioniert.

Da sich der Wert sensor.viessmann_gridbox_grid im Normalfall sekündlich ändert, ist das ein Indiz dafür, dass das Addon sich aufgehängt hat, wenn er sich länger nicht ändert.
Nach 30 Sekunden ohne Änderung wird das Addon beendet und nach 45 Sekunden wieder neugestartet.
Direkt Neustarten hat zu Problemen geführt, daher zwei Einträge in der automations.yaml.

siehe Einträge in der automations.yaml

- alias: gridbox_trigger
  trigger:
    - platform: state
      entity_id: sensor.viessmann_gridbox_grid
      # The sensor remained in its current state for 30 seconds
      for: "00:00:30"
  action:
    - service: hassio.addon_stop
      data:
        addon: "2798059d_gridbox_connector"

- alias: gridbox_trigger_2
  trigger:
    - platform: state
      entity_id: sensor.viessmann_gridbox_grid
      # The sensor remained in its current state for 45 seconds
      for: "00:00:45"
  action:
    - service: hassio.addon_start
      data:
        addon: "2798059d_gridbox_connector"

**Comment by unl0ck** [comment]
@zionusxx ich muss unbedingt mal ein dev aufsetzen womit ich rumspielen kann, werd es vllt heute schaffen.

**Comment by unl0ck** [comment]
@zionusxx Hast du noch Probleme? Demnächst kommt ein Umbau mit s6 overlay dann funktioniert der watchdog und dann sollte es gar kein Problem mehr sein. Duerfte aber auch so nemme auftreten
