### ISSUE TITLE
add-on not running

### ISSUE THREAD

**Issue by don-o-mat** [unl0ck/homeassistant-addon-viessmann-gridbox#23]
**Describe the bug**
After the latest update 1.9x the add-on won't run in home assistant anymore. Shortly after starting it, it will stop again. 

**To Reproduce**
Updated the add-on from 1.5x and restarted. Add-on will stop seconds after restart. 

**Expected**
After restart the add-on is running stable.

**Comment by unl0ck** [comment]
Kannst du den log schicken bitte ? Bei mir laeufts mit freundlichen GrüßenSimon HelmingOn 8. May 2024, at 07:55, don-o-mat ***@***.***> wrote:﻿
Assigned #23 to @unl0ck.

**Comment by unl0ck** [comment]
@don-o-mat hab mal reverted auf 1.5.0 bis ich unit test hab oder paar test daten

**Comment by don-o-mat** [comment]
Ich hoffe das ist korrekt, im Log steht noch viel mehr, aber das scheint sich zu wiederholen. Danke für deine Mühe!

Ich kann auch versuchen das add-on zu entfernen usw, wenn das hilft. 

Danke @unl0ck 

/build
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/build/GridboxConnector/__main__.py", line 137, in <module>
    appliance_id = measurement["battery"]["applianceID"]
KeyError: 'applianceID'
Start Viessmann Connector
{'grant_type': 'http://auth0.com/oauth/grant-type/password-realm', 'username': '****', 'password': '***', 'audience': 'my.gridx', 'client_id': '*****', 'scope': 'email openid', 'realm': 'viessmann-authentication-db'}
{'access_token': '***OiJhdXRoMHw2NDdiMjlkNDBhMmUyYjBhODBlMWY0MDYiLCJhdWQiOlsibXkuZ3JpZHgiLCJodHRwczovL2dyaWR4LmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTUxNjEzMzksImV4cCI6MTcxNTI0NzczOSwic2NvcGUiOiJlbWFpbCBvcGVuaWQiLCJndHkiOiJwYXNzd29yZCIsImF6cCI6Im9acHI5MzRJa244T1pPSFRKRWNyZ1hramlvMEkwUTdiIn0.uc5d1dsMcQdrlSsFMdhjLDobqWqQGe_rlm1BO31Crh1cbXVi7tM8CCi-G1oDwuZnu6tlSCbN1deQi48DUzFYfCCsopSuRL9vhcoh24j-gquSH6WIlD70g93DAM0IUF0-28zW2IQy93PzQejJGyF8muZMnY6R7BXnJ6xMhmvMh3caRHV8QC7xSuXbjW383mSdLfefccYWj8DsdqY-yYgls3rUpB1T0Oc_padfYC1ihOYxuy_kSoRxzrU5dJPVOFk0uLO8VwJpbHxhe464trme5ljYiAVHhKM7OoVoYfMsCvaGifGyVqP0Pf8U2dNFr2KC8O7mUJnLQAxZ1DoblygQ5Q', 'id_token': '****WVkIjpmYWxzZSwiaXNzIjoiaHR0cHM6Ly9ncmlkeC5ldS5hdXRoMC5jb20vIiwiYXVkIjoib1pwcjkzNElrbjhPWk9IVEpFY3JnWGtqaW8wSTBRN2IiLCJpYXQiOjE3MTUxNjEzMzksImV4cCI6MTcxNTE5NzMzOSwic3ViIjoiYXV0aDB8NjQ3YjI5ZDQwYTJlMmIwYTgwZTFmNDA2In0.JwWX07gUKZf_ZHJfTHp1BZ2MflfPrxwg-DhKsqUL-XFQZ37PzU86nlgQh154QWysbOMVWKwr-UUk1RtdGljOwcfTEC9ZlExV3sB188xEuNm2xYBQYeQ5OE4FyB53ZAxLXA9THbXgM_--l2LUfJGs7JyIQiKUd8N68cS_MJFNkzvPk6LP-zBE1lgNcoPo-J0PNbRr2IP3A-1fduzsR1_kHE_CdM6vQIMfbB5zHS46-Mmysa2YiASDvjDNVqa41TN1J9WtQWkTG8Fw-B4lNAp9mrl1Lo65SbpNFO8BtX-AlwwcZXF8wa_7AtAGa1HeT9Y8EODDFoYyMWVwuN_9jw8wsw', 'scope': 'email openid', 'expires_in': 86400, 'token_type': 'Bearer'}
{'batteries': [{'applianceID': '97af25d0-3791-48cc-857c-14aaac749267', 'capacity': 10000, 'nominalCapacity': 10000, 'power': -853, 'remainingCharge': 7700, 'stateOfCharge': 0.77}], 'battery': {'capacity': 10000, 'nominalCapacity': 10000, 'power': -853, 'remainingCharge': 7700, 'stateOfCharge': 0.77}, 'consumption': 600, 'directConsumption': 600, 'directConsumptionEV': 0, 'directConsumptionHeatPump': 0, 'directConsumptionHeater': 0, 'directConsumptionHousehold': 600, 'directConsumptionRate': 0.3968253968253968, 'grid': -59, 'gridMeterReadingNegative': 14081760000, 'gridMeterReadingPositive': 7393320000, 'measuredAt': '2024-05-08T09:42:18Z', 'photovoltaic': 1512, 'production': 1512, 'selfConsumption': 1453, 'selfConsumptionRate': 0.9609788359788359, 'selfSufficiencyRate': 1, 'selfSupply': 600, 'totalConsumption': 600}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by don-o-mat** [comment]
Die reverted Version läuft wieder fein. Habe das add-on entfernt und neu hinzugefügt.

**Comment by unl0ck** [comment]
@don-o-mat  wäre nicht notwendig gewesen, hätte ausgereicht, wenn du einfach auf 1.9.10 hoch zu gehen. 
aber jetzt weiß ich woran es lag, ich kann das jetzt wieder einbauen, wer das in Dev machen könntest du einmal dev testen, sobald eine neue version davon verfügbar ist?

**Comment by unl0ck** [comment]
@don-o-mat  bitte teste dev 1.9.11

**Comment by don-o-mat** [comment]
> @don-o-mat bitte teste dev 1.9.11

Ich würde das gerne machen, weiß aber nicht wie. 
¯\_(ツ)_/¯

**Comment by don-o-mat** [comment]
Prima, danke! ☺️ 

Startet leider nicht. 

Hier das Log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun example (no readiness notification)
s6-rc: info: service legacy-services successfully started
total 12K    
     4 drwxr-xr-x    2 root     root        4.0K May  9 11:43 .
     4 drwxr-xr-x    1 root     root        4.0K May  9 11:43 ..
     4 -rw-------    1 root     root          80 May  9 11:43 options.json
{
  "username": "***",
  "password": "***",
  "wait_time": 2
}total 16K    
     4 drwxr-xr-x    1 root     root        4.0K May  8 14:18 .
     4 drwxr-xr-x    1 root     root        4.0K May  9 11:43 ..
     4 drwxr-xr-x    2 root     root        4.0K May  8 14:18 GridboxConnector
     4 -rw-r--r--    1 root     root         504 May  8 14:18 cloudSettings.json
/build
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/build/GridboxConnector/__main__.py", line 141, in <module>
    battery_sum.set_values(state_of_charge, capacity, power, remaining_charge)
AttributeError: 'Battery' object has no attribute 'set_values'
Start Viessmann Connector
{'grant_type': 'http://auth0.com/oauth/grant-type/password-realm', 'username': '***', 'password': '***', 'audience': 'my.gridx', 'client_id': 'oZpr934Ikn8OZOHTJEcrgXkjio0I0Q7b', 'scope': 'email openid', 'realm': 'viessmann-authentication-db'}
{'access_token': 'eeyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik16UkRSakU1UVRrd1JEQXhOVU15UlRnMVFrRTNNemRCUmpZNE5rRTFOamRCTjBZd1FrWkdOQSJ9.eyJpc3MiOiJodHRwczovL2dyaWR4LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NDdiMjlkNDBhMmUyYjBhODBlMWY0MDYiLCJhdWQiOlsibXkuZ3JpZHgiLCJodHRwczovL2dyaWR4LmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTUyNDc3ODgsImV4cCI6MTcxNTMzNDE4OCwic2NvcGUiOiJlbWFpbCBvcGVuaWQiLCJndHkiOiJwYXNzd29yZCIsImF6cCI6Im9acHI5MzRJa244T1pPSFRKRWNyZ1hramlvMEkwUTdiIn0.SO0UoaB92dkSQt6MrdkTMbgAcEhdjJs3hr6HsM96IZsIKeRXvFWbYku_rUAdWLwwBJ8S8VDJ-FoOU2cGCdDKNy7vFPMLlGFWjgQitzOJOoHvaxN4kU5z2SmDH2GxunbTYRUGP8q2Kz9yX3TnEelcmtBUC1yhb9n_U-24mPcUOWxH4mg6QRWP_NUJW_6DaJK2ZWaIBnQT3fyR8m9O9pEj9s3qDmaBzi99z1rHTEr97C1v6SzGPwQ2tA-3wq_gbYTrzSl_EyCEpZQf_gXR7Q1oZ48wARWjh531WmSvcMx3ecJYHhw5WjM6PfRLMPA0wEvv7JYoFd7PK6BEZFTQimDM6A', 'id_token': 'eeyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik16UkRSakU1UVRrd1JEQXhOVU15UlRnMVFrRTNNemRCUmpZNE5rRTFOamRCTjBZd1FrWkdOQSJ9.eyJlbWFpbCI6IjU1NS01NTVAZ214Lm5ldCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaXNzIjoiaHR0cHM6Ly9ncmlkeC5ldS5hdXRoMC5jb20vIiwiYXVkIjoib1pwcjkzNElrbjhPWk9IVEpFY3JnWGtqaW8wSTBRN2IiLCJpYXQiOjE3MTUyNDc3ODgsImV4cCI6MTcxNTI4Mzc4OCwic3ViIjoiYXV0aDB8NjQ3YjI5ZDQwYTJlMmIwYTgwZTFmNDA2In0.iSF7_6_0yG39Sv0f4i4wqBTMukUJ-BHacnVHusvWvBvYwRWHi1JHhqPbF-LXQITJj1sXZ2PFAVoo9-PDMTVvQg2FuFtrtJMbjsJu6Uq59mUuT4AMGDwrF45trrkGrnncC4AhTpJm1qrXXv1NUjk2C8Eo7Xcec0ngQjiu8_V4bC_eEyiK35RpzsGRNJbQDTeN5PkwaJ0RzN-uIUoLrtzFVl6TV65oV81swFpxpefn4b5uxs2kt5Z8WuPHs9c2J0XVjxr9o1xG5GMaZQ8Ibk0yO0o1GEFN3E6ivMUBWNEcdKFjn3U855NwZgIIvLsjHpmcUceIva5ToqBdOggoVXHgmQ', 'scope': 'email openid', 'expires_in': 86400, 'token_type': 'Bearer'}
{'batteries': [{'applianceID': '97af25d0-3791-48cc-857c-14aaac749267', 'capacity': 10000, 'nominalCapacity': 10000, 'power': 0, 'remainingCharge': 10000, 'stateOfCharge': 1}], 'battery': {'capacity': 10000, 'nominalCapacity': 10000, 'power': 0, 'remainingCharge': 10000, 'stateOfCharge': 1}, 'consumption': 2529, 'directConsumption': 2529, 'directConsumptionEV': 0, 'directConsumptionHeatPump': 0, 'directConsumptionHeater': 0, 'directConsumptionHousehold': 2529, 'directConsumptionRate': 0.6555209953343701, 'grid': -1329, 'gridMeterReadingNegative': 14101920000, 'gridMeterReadingPositive': 7394400000, 'l1CurtailmentPower': 0, 'l2CurtailmentPower': 0, 'l3CurtailmentPower': 0, 'measuredAt': '2024-05-09T09:43:08Z', 'photovoltaic': 3858, 'production': 3858, 'selfConsumption': 2529, 'selfConsumptionRate': 0.6555209953343701, 'selfSufficiencyRate': 1, 'selfSupply': 2529, 'totalConsumption': 2529}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by unl0ck** [comment]
Danke ich arbeite gerade an den unittest du warst nur schneller, werde das beheben, war ein leichtsinnsfehler danke für den test

**Comment by unl0ck** [comment]
@don-o-mat 1.9.12 sollte bereit stehen

**Comment by don-o-mat** [comment]
Die 1.9.12 scheint gut zu laufen! Top! :D

**Comment by unl0ck** [comment]
Hab noch keine Unittest du(wenn ich du sagen darf) warst mein Tester vielen Dank dafür dein response werde ich wiederverwenden für meine Tests, 
Werde das demnächst auf Prod packen.

Danke nochmal

@don-o-mat

**Comment by unl0ck** [comment]
@don-o-mat kannst du nen Screenshot von der geraeteuebersicht schicken damit ich mal sehe wie das aussieht mit den mehreren Batterien?

**Comment by don-o-mat** [comment]
@unl0ck Du ist immer fein. 

Freut mich, wenn ich ein kleines bisschen helfen konnte. Bin immer noch sehr dankbar, dass du dieses tolle add-on gebaut hast. 

Wenn du mehr Infos brauchst oder Screenshots usw kannst du mir gerne jederzeit schreiben. 

Habe (nur) einen Akku und zwei Wechselrichter. 
![Screenshot_20240509-183300](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/168067059/3633e09a-0276-4c28-8fb2-6b1ee1d292bf)

**Comment by unl0ck** [comment]
Beide wechselrichter siehst du aktuell aber nicht oder ?

**Comment by unl0ck** [comment]
@don-o-mat  ich hab ein fehler eingebaut bei den einzelnen Batterien dort wurden die falsche werte genommen ist hier nicht aufgefallen weil du nur eine hast.
ich hab jetzt mal ne 1.10.1 auf Dev gepackt hab da einiges umgebaut da ist mir der Fehler aufgefallen, kannst du bitte das einmal testen?

**Comment by don-o-mat** [comment]
> Beide wechselrichter siehst du aktuell aber nicht oder ?

Die Gridbox macht daraus via Geräteeinrichtung eine Einheit. Ich sehe nur die Summe aller Werte aus beiden. Theoretisch kann ich einen Wechselrichter als Volleinspeiser definieren, dann zeigt die Gridbox die PV Leistung der beiden getrennt. Die Werte erscheinen dann aber nicht 100% korrekt und die Statistiken fehlen.

**Comment by don-o-mat** [comment]
> @don-o-mat ich hab ein fehler eingebaut bei den einzelnen Batterien dort wurden die falsche werte genommen ist hier nicht aufgefallen weil du nur eine hast. ich hab jetzt mal ne 1.10.1 auf Dev gepackt hab da einiges umgebaut da ist mir der Fehler aufgefallen, kannst du bitte das einmal testen?

Gerne. 
Es scheint gut zu laufen. Sehe die Werte des Akkus nun zweimal. Die Werte für "battery_sum_level" und "battery_sum_power" scheinen noch nicht zu stimmen. 
![Screenshot_20240510-025641](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/168067059/18416874-07a2-4d19-8120-3babb3ddfab2)

**Comment by unl0ck** [comment]
@don-o-mat  ich schau es mir an, ich hab Battery 0 rausgeworfen weil das ist ja doof hab daraus Battery 1 gemacht deswegen siehst du vermutlich noch 0 wegen dem self schau ich mir heute an, 
hey mega cool das ich dich grad nutzen kann, muss aber unbedingt auf unit Tests umsteigen, ich weiß ja nicht wofür du deine PV in Home assistant nutzt und ich will dich damit auch ned nerven, aber ich danke dir aufjedenfall nochmal dafür

**Comment by unl0ck** [comment]
@don-o-mat  ich hab tatsächlich was gefunden wo falsch war wo der wert falsch hinzugefügt wurde. bezüglich Batterie0 die gibt es nicht mehr, wenn die nicht von alleine verschwindet musst du wohl das mqtt device löschen und nochmal anlegen lassen über das Addon, mit 1.10.2 sollte nun alles soweit passen.
hab jetzt auch schon ne halbwegs gute Grundlade geschaffen das ich zukünftig unittests nutzen kann, noch kleinere Probleme mit meiner Entwicklungsumgebung, dass die nicht so will wie ich, aber man kann sie ausführen :D

**Comment by don-o-mat** [comment]
Tolle Fortschritte @unl0ck !

Hier ein aktueller Sreenshot der 1.10.2:
![Screenshot_20240511-083940](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/168067059/a5f2951f-fc54-46d3-a4a1-db195487fdfa)

**Comment by unl0ck** [comment]
Top ich glaub so können wir es lassen,
Ja bezüglich hört auf bin ich dran da gab es einen workaround @don-o-mat das wird aber bissle länger dauern

**Comment by unl0ck** [comment]
@don-o-mat Ich hab jetzt mal auf das neue Layer umgestellt somit funktioniert der watchdog ist noch auf Edge wird aber heute denke ich auf dev wandern

**Comment by don-o-mat** [comment]
Toller Fortschritt! Das sieht alles sehr gut aus @unl0ck

Eine Kleinigkeit, könnte auch an Home Assistant liegen: Das add-on läuft, aber wird nicht als gestartet angezeigt. Die Werte der Gridbox kommen sauber rein. 

Auch im Log kommen ständig neue Zeilen hinzu.
![Screenshot_20240515-175501](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/168067059/a6834959-cc51-442d-be9e-e55cc4282494)

![Screenshot_20240515-175743](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/168067059/9795ef88-0819-44ea-9fcd-e1436f4601a6)

**Comment by unl0ck** [comment]
Home assistant ist manchmal langsam in der Aktualisierung, kann sein das es nicht up to Date war, 
Ja die log Nachrichten hab ich auch gesehen, kommen noch weg stören aber erst mal keinen

**Comment by unl0ck** [comment]
@don-o-mat  ich schließ den jetzt mal weil an sich funktioniert es jetzt ja
