### ISSUE TITLE
Mehr Sensoren möglich?

### ISSUE THREAD

**Issue by wgretzke** [unl0ck/homeassistant-addon-viessmann-gridbox#27]
Super Programm - Danke!
Ist es auch möglich, noch "E-Auto" als einzelne Auswertung zu integrieren?
![VX3](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/170232821/53620dd1-0b8c-477e-8e79-8024d7a8ee74)

**Comment by unl0ck** [comment]
Kannst du mir das json schicken davon? 
Dann wirds einfacher, hab zwar die Doku aber so hätte ich direkt nen echten Wert @wgretzke

**Comment by wgretzke** [comment]
wenn ich auch nur die leiseste Idee hätte, wie, mache ich es gerne ...

**Comment by unl0ck** [comment]
Wenn du diese Seite siehst klick f12 dann sollte die Entwickler Konsole aufgehen dort müsste irgendwo Network stehen, wenn das nicht hilft schreib ich vielleicht morgen mal wenn ich dazu komme ne Anleitung,

@wgretzke Ich Versuch den Verbrauch vom Auto diese Woche hinzuzufügen, reicht dir das ?

**Comment by unl0ck** [comment]
@wgretzke  du darfst gerne nen stern bei dem python lib hinterlassen würde gerne meine 16 Sterne erreichen, 
https://github.com/unl0ck/viessmann-gridbox-connector

bitte prüfe ob es das ist was du brauchst, aber die testdaten würd ich gerne dennoch haben. 
damit ich meine tests verbessern kann, wenn ich sie endlich mal geschrieben hab -.- :D

**Comment by wgretzke** [comment]
> @wgretzke du darfst gerne nen stern bei dem python lib hinterlassen würde gerne meine 16 Sterne erreichen, https://github.com/unl0ck/viessmann-gridbox-connector
> 
erledigt!

> bitte prüfe ob es das ist was du brauchst, aber die testdaten würd ich gerne dennoch haben. damit ich meine tests verbessern kann, wenn ich sie endlich mal geschrieben hab -.- :D
>
Alles funktioniert wie erwartet / gewünscht - Vielen Dank!

**Comment by wgretzke** [comment]
Oh, sorry, doch nicht ganz :(
Die Werte sind - wie ja der Name "DirectConsumptionEV" richtig besagt - der Direktverbrauch, also der von der PV Anlage in diesem Moment abgedeckte Verbrauch. Wenn ich aber mein E-Auto anschließe mit 11KW, aber die Sonne nur 7kW erzeugt und der Rest aus der Batterie oder dem Netz kommt, zeigt eben "DirectConsumptionEV" die 7kW an, nicht aber die 11kW, 
Mich würde aber eben auch der die Gesamtladeleistung zum EV in der Anzeige interessieren.
Ist deshalb besonders interessant, weil in der Viessmann App nur die Summe vom Direktverbrauch in kWh anzeigt, der hier gezeigte Wert ist mir in der App bisher nirgends ersichtlich gewesen.
Wie kann ich helfen?

**Comment by unl0ck** [comment]
wenn du so einen fall hast, kannst auf https://mygridbox.viessmann.com/ auf dem pc folgendes machen.
nimm den Edge öffne die seite log dich ein und dann geh auf live daten und drücke F12 dann solltest du folgendes sehen
![image](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/25794700/907844df-4082-4dd6-afb2-997a0255673e)
hab in rot makiert wo du drauf drücken musst, und grün was ich brauche

**Comment by unl0ck** [comment]
der parameter sagt nur directConsumptionEV
double
Power/energy consumed by the EV through production directly.
also scheinbar nur was man produziert nicht was man hat.
ich nutze evcc.io für solche dinge

**Comment by unl0ck** [comment]
Ja aber kannst du davon kein Bild machen sondern mir das schicken? 
Irgendwie sieht deins anders aus als bei mir

**Comment by wgretzke** [comment]
> Ja aber kannst du davon kein Bild machen sondern mir das schicken? Irgendwie sieht deins anders aus als bei mir

[Viessmann.xlsx](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/files/15487389/Viessmann.xlsx)
 habs mal in ein xls gepackt ...

**Comment by unl0ck** [comment]
Ne Textdatei wäre praktischer 😅🙈

Ich schau nachher mal ob das dennoch geht 
Aber wie du siehst da gibt es kein gesamt, müsstest du selber zusammen rechnen

**Comment by wgretzke** [comment]
aber es gibt 

evChargingStation:   {power: 0}
power: 0

da ich bei mir einen zusammengefassten Wert sehe, könnte das sein - oder eben die beiden Wallboxen darunter, evChargingStations 0 und 1;
hier zeigt es beides 0, aber es fließt auch gerade nichts. Wenn ich die Werte lesen könnte, würde ich mal beide Autos an beide Wallboxen hängen ...

**Comment by wgretzke** [comment]
zur Info: versuche, das morgen zu machen, habe gerade nicht genügend Autos und Sonne ;)

Auch zu deiner Info: Update 2.5.7 funktioniert bei mir nicht, geht immer wieder aus ... bin zurück aus 2.1.3, die Version funktioniert super. (Ich hatte 2.3.0,,die hat auch stabil funktioniert, aber kein Backup, und daher jetzt wieder 2.1.3)

**Comment by unl0ck** [comment]
Versteh ich nicht bei mir läuft sie, -.- 
Log Level gesetzt?

**Comment by unl0ck** [comment]
![IMG_0182](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/25794700/f47cb5cc-e780-46ef-9721-c9fce6072af2)

**Comment by unl0ck** [comment]
Ich Schau es mir an, aber denke sollte möglich sein, solang ich alle Daten habe kann man die zusammen führen und co

**Comment by wgretzke** [comment]
edge 2.6.0 geht immer „aus, d.h. nach dem starten bleibt es nur wenige Sekunden an.

Und außer 2 Stromwerten habe ich nichts zum Auslesen gefunden.
Was mache ich falsch?

 

Von: unl0ck ***@***.***> 
Gesendet: Dienstag, 4. Juni 2024 14:57
An: unl0ck/homeassistant-addon-viessmann-gridbox ***@***.***>
Cc: wgretzke ***@***.***>; Mention ***@***.***>
Betreff: Re: [unl0ck/homeassistant-addon-viessmann-gridbox] Mehr Sensoren möglich? (Issue #27)

 

kannst du dir mal edge installieren? @wgretzke <https://github.com/wgretzke>  dort hab ich EV eingebaut.
und kannst du mir bitte im folgenden format nen output geben

{
    "consumption": 186,
    "directConsumption": 186,
    "directConsumptionEV": 0,
    "directConsumptionHeatPump": 0,
    "directConsumptionHeater": 0,
    "directConsumptionHousehold": 186,
    "directConsumptionRate": 0.2243667068757539,
    "grid": -643,
    "gridMeterReadingNegative": 5144040000,
    "gridMeterReadingPositive": 31539960000,
    "measuredAt": "2024-06-04T12:54:32Z",
    "photovoltaic": 829,
    "production": 829,
    "selfConsumption": 186,
    "selfConsumptionRate": 0.2243667068757539,
    "selfSufficiencyRate": 1,
    "selfSupply": 186,
    "totalConsumption": 186
}

indem du folgendes machst
image.png (view on web) <https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/25794700/ff329483-3277-4888-a286-5564c836dffd> 

darauf klicken. dann könnte ich mit deinen daten testen.

**Comment by wgretzke** [comment]
Also es funktioniert eine Zeit, aber dann steigt es wieder aus, und hier ist so eine Fehlermeldung, das "Current_l3" nicht existiert und bei mir auch nur "Sum Current L1" und "Sum Current L2" erscheinen ... die Zeischenfolge "EV" existiert übrigens weiterhin nur einmal, bei "DirectConsumptionEV"

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/build/GridboxConnector/__main__.py", line 55, in <module>
    viessmann_gridbox_connector.update_sensors(result)
  File "/build/GridboxConnector/ha_viessmann_gridbox_connector.py", line 153, in update_sensors
    self.ev_sum.set_states(power, state_of_charge, current_l1, current_l2, current_l3)
  File "/build/GridboxConnector/ha_viessmann_ev_charging_station.py", line 60, in set_states
    self.current_l3.set_state(current_l3)
    ^^^^^^^^^^^^^^^
AttributeError: 'HAViessmannEVChargingStation' object has no attribute 'current_l3'. Did you mean: 'current_l1'?
[17:45:19] INFO: Service gridboxconnector exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service gridboxconnector: stopping
s6-rc: info: service gridboxconnector successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by unl0ck** [comment]
2.6.2 sollte helfen

**Comment by wgretzke** [comment]
also Fehlermeldung gibt es keine, Current L3 ist auch da.
Muss morgen mal Werte testen ...

**Comment by wgretzke** [comment]
{
    "batteries": [
        {
            "applianceID": "2423417f-81af-473b-9168-7d5ffb8d5641",
            "capacity": 10000,
            "nominalCapacity": 10000,
            "power": 3126,
            "remainingCharge": 9800,
            "stateOfCharge": 0.98
        }
    ],
    "battery": {
        "capacity": 10000,
        "nominalCapacity": 10000,
        "power": 3126,
        "remainingCharge": 9800,
        "stateOfCharge": 0.98
    },
    "consumption": 923.6,
    "directConsumption": 5728,
    "directConsumptionEV": 5728,
    "directConsumptionHeatPump": 0,
    "directConsumptionHeater": 0,
    "directConsumptionHousehold": 0,
    "directConsumptionRate": 0.8414867048626414,
    "evChargingStation": {
        "power": 7930.4
    },
    "evChargingStations": [
        {
            "applianceID": "0ff421b0-7603-4fca-9cc2-211be7982be6",
            "currentL1": 12.07,
            "currentL2": 11.89,
            "currentL3": 10.52,
            "plugState": "PLUGGED_ON_STATION_AND_PLUGGED_ON_VEHICLE",
            "power": 7930.4,
            "readingTotal": 228408.05777777778
        },
        {
            "applianceID": "87f20de8-ef1a-49d0-bd71-5e4508db0d6e",
            "currentL1": 0,
            "currentL2": 0,
            "currentL3": 0,
            "plugState": "PLUGGED_ON_STATION",
            "power": 0,
            "readingTotal": 155763
        }
    ],
    "grid": -1079,
    "gridMeterReadingNegative": 6663600000,
    "gridMeterReadingPositive": 9370440000,
    "l1CurtailmentPower": 0,
    "l2CurtailmentPower": 0,
    "l3CurtailmentPower": 0,
    "measuredAt": "2024-06-05T12:53:23Z",
    "photovoltaic": 6807,
    "production": 6807,
    "selfConsumption": 5728,
    "selfConsumptionRate": 0.8414867048626414,
    "selfSufficiencyRate": 1,
    "selfSupply": 8854,
    "totalConsumption": 8854
}

![image](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/170232821/c47391d4-f986-48d1-94cb-cb040b6797bc)


![image](https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/assets/170232821/268fa0db-a3a3-4c0c-b195-992088f7f64a)

Zusammenfassend:
"Power Sum" scheint den EV Wallbox Verbrauch zu zeigen, "Current" ist wohl von der anderen Wallbox, kann ich gerade nicht testen.

**Comment by unl0ck** [comment]
super genau so hab ich mir das vorgestellt.  mit der json ;)

**Comment by wgretzke** [comment]
Hallo nochmal, 
jetzt habe ich alles ausprobiert - es funktioniert super, alles, was mich interessiert hat, kann ich auslesen und verarbeiten.
es gibt 4 Positionen, welche bei mir immer "0" anzeigen, vielleicht sind die für eine andere Konfiguration, ich wollte es nur anmerken: "sum Reading Total" sowie "sum Current L1-3"
Tolle Arbeit - Danke!

**Comment by unl0ck** [comment]
Scheinbar schicken die dann nur eine 0 kannst du ja mal schauen auf der Webseite genau diese Daten lese ich auch
